name: Lobby
version: 1.0.0
author: Brentspine & LvkasDev for Kanyuji.de
api-version: 1.16
main: de.kanyuji.lobby.Main
depend:
  - api

commands:
  setup:
    description: Setup
  spawn:
    description: Spawn
  discord:
    description: Discord
  messagelater:
    description: Message Later
  lobbytest:
    description: Lobby Test
    permission: lobby.debug
  gamemode:
    description: Gamemode
    aliases: gm
    permission: lobby.gamemode
