name: api
version: 1.0.0
author: Brentspine
api-version: 1.16
main: de.brentspine.kanyujiapi.KanyujiAPI
depend:
  - ProtocolLib

commands:
  coins:
    description: Coins
  playtime:
    description: Playtime
  apitest:
    description: Testing
  friends:
    description: Friends
  keys:
    description: Keys
    aliases:
      - chestkeys
      - key
  ignore:
    description: Ignore